apiVersion: v1
kind: Service
metadata:
  name: rlouk-service
spec:
  type: NodePort
  selector:
    myapp: rlouk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlouk
  labels:
    myapp: rlouk
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: rlouk
  template:
    metadata:
      labels:
        myapp: rlouk
    spec:
      containers:
      - name: web
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
