name: Hello-World

on: push

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
    - name: environment-variable
      run: set
    - name: Python
      run: Python 3.10.6
    - name: my-step
      run: echo "Hello World"
    
